;;; identity
(setopt user-mail-address "alexforsale@yahoo.com"
        user-full-name "Kristian Alexander P")

;;; `+config/org-directory'
(cond ((file-directory-p (expand-file-name "Sync/org" (getenv "HOME")))
       (customize-set-variable '+config/org-directory (expand-file-name "Sync/org" (getenv "HOME"))
                               "`+config/org-directory' set on Linux Syncthing folder."))
      ((string-match-p "microsoft" (shell-command-to-string "uname -a"))
       (if (file-directory-p "/mnt/c/Users/SyncthingServiceAcct/Default Folder/org")
           (customize-set-variable '+config/org-directory "/mnt/c/Users/SyncthingServiceAcct/Default Folder/org"
                                   "`+config/org-directory set on Windows.'"))))
(setopt org-directory +config/org-directory)

;;; custom functions
(defun my/move-line-or-region-internal (arg)
   (cond
    ((and mark-active transient-mark-mode)
     (if (> (point) (mark))
            (exchange-point-and-mark))
     (let ((column (current-column))
              (text (delete-and-extract-region (point) (mark))))
       (forward-line arg)
       (move-to-column column t)
       (set-mark (point))
       (insert text)
       (exchange-point-and-mark)
       (setq deactivate-mark nil)))
    (t
     (beginning-of-line)
     (when (or (> arg 0) (not (bobp)))
       (forward-line)
       (when (or (< arg 0) (not (eobp)))
            (transpose-lines arg))
       (forward-line -1)))))

(defun my/move-line-or-region-down (arg)
   "Move region (transient-mark-mode active) or current line
  arg lines down."
   (interactive "*p")
   (my/move-line-or-region-internal arg))

(defun my/move-line-or-region-up (arg)
   "Move region (transient-mark-mode active) or current line
  arg lines up."
   (interactive "*p")
   (my/move-line-or-region-internal (- arg)))

(global-set-key (kbd "C-c M-n") 'my/move-line-or-region-down)
(global-set-key (kbd "C-c M-p") 'my/move-line-or-region-up)

(defvar my/move-line-or-region-repeat-map
  (let ((map (make-sparse-keymap)))
    (define-key map "n" #'my/move-line-or-region-down)
    (define-key map "p" #'my/move-line-or-region-up)
    map)
  "Keymap for my/move-line-or-region-repeat-map")
(put 'my/move-line-or-region-down 'repeat-map 'my/move-line-or-region-repeat-map)
(put 'my/move-line-or-region-up 'repeat-map 'my/move-line-or-region-repeat-map)

;;; enable `delete-selection-mode'
(use-package delsel
  :ensure nil
  :config
  (delete-selection-mode 1))

;;; base
(use-package emacs
  :ensure nil
  :config
  (transient-mark-mode 1)
  (setopt use-short-answers t
          delete-by-moving-to-trash t
          load-prefer-newer t
          read-buffer-completion-ignore-case t
          read-file-name-completion-ignore-case t
          inhibit-startup-screen t
          indicate-empty-lines t
          frame-resize-pixelwise t))

;;; repeat
(use-package repeat
  :ensure nil
  :config
  (repeat-mode 1))

;;; enable `global-font-lock-mode'
(use-package font-core
  :ensure nil
  :config
  (global-font-lock-mode 1))

;;; winner
(use-package winner
  :ensure nil
  :init
  (winner-mode +1)
  :config
  (setopt winner-boring-buffers '("*Completions*" "*Compile-Log*" "*inferior-lisp*" "*Fuzzy Completions*"
                                  "*Apropos*" "*Help*" "*cvs*" "*Buffer List*" "*Ibuffer*"
                                  "*esh command on file*")))

;;; completion
(use-package completion-preview
  :ensure nil
  :config
  (global-completion-preview-mode)
  (push 'org-self-insert-command completion-preview-commands))

(use-package minibuffer
  :ensure nil
  :config
  (setopt minibuffer-visible-completions t
          completion-styles '(basic partial-completion flex emacs22)))

(use-package simple
  :ensure nil
  :config
  (global-visual-line-mode t)
  (column-number-mode t)
  (line-number-mode t)
  (setopt completion-auto-wrap t
          completion-auto-select 'second-tab
          completion-auto-help nil
          completion-ignore-case t)
  (setq-default indent-tabs-mode nil))

(use-package icomplete
  :ensure nil
  :config
  (fido-vertical-mode 1))

;;; saveplace
(use-package saveplace
  :init
  (save-place-mode 1))

;;; recentf
(use-package recentf
  :bind ("C-c f" . recentf)
  :commands recentf-open-files
  :init
  (recentf-mode 1)
  :custom
  (recentf-auto-cleanup t)
  (recentf-max-saved-items 250)
  (recentf-max-menu-items 300)
  (recentf-exclude
   `("/elpa/" ;; ignore all files in elpa directory
     "recentf" ;; remove the recentf load file
     ".*?autoloads.el$"
     "treemacs-persist"
     "company-statistics-cache.el" ;; ignore company cache file
     "/intero/" ;; ignore script files generated by intero
     "/journal/" ;; ignore daily journal files
     ".gitignore" ;; ignore `.gitignore' files in projects
     "/tmp/" ;; ignore temporary files
     "NEWS" ;; don't include the NEWS file for recentf
     "bookmarks"  "bmk-bmenu" ;; ignore bookmarks file in .emacs.d
     "loaddefs.el"
     "^/\\(?:ssh\\|su\\|sudo\\)?:" ;; ignore tramp/ssh files
     (concat "^" (regexp-quote (or (getenv "XDG_RUNTIME_DIR")
                                   "/run"))))))

;;; autorevert
(use-package autorevert
  :ensure nil
  :config
  (global-auto-revert-mode t)
  (setopt auto-revert-interval 60
          global-auto-revert-non-file-buffers t))

;;; which-key
(use-package which-key
  :ensure nil
  :init
  (which-key-mode 1))

;;; files
(use-package files
  :ensure nil
  :hook
  ((prog-mode text-mode) . auto-save-visited-mode)
  :config
  (auto-save-visited-mode 1)
  (nconc
   auto-mode-alist
   '(("/LICENSE\\'" . text-mode)
     ("\\.log\\'" . text-mode)
     ("rc\\'" . conf-mode)
     ("\\.\\(?:hex\\|nes\\)\\'" . hexl-mode)))
  (setopt auto-save-visited-interval 10
          revert-without-query (list ".")
          find-file-suppress-same-file-warnings t
          find-file-visit-truename t
          confirm-kill-processes nil
          version-control t
          backup-by-copying t
          backup-directory-alist `(("." . ,(expand-file-name ".backup" user-emacs-directory)))
          auto-save-list-file-prefix (expand-file-name ".autosave/" user-emacs-directory)
          require-final-newline t
          find-file-visit-truename t
          auto-mode-case-fold nil)
  :hook
  ((prog-mode text-mode) . auto-save-visited-mode))

;;; savehist
(use-package savehist
  :ensure nil
  :config
  (savehist-mode 1)
  (setopt savehist-additional-variables
          '(command-history
            kill-ring
            register-alist
            mark-ring
            global-mark-ring
            search-ring
            regexp-search-ring)))

;;; project
(use-package project
  :ensure nil
  :config
  (setopt project-mode-line t))

;;; mouse
(use-package mouse
  :ensure nil
  :config
  (setopt mouse-yank-at-point t))

;;; subword
(use-package subword
  :ensure nil
  :init
  (global-subword-mode 1))

;;; text-mode
(use-package text-mode
  :ensure nil
  :hook (((text-mode prog-mode) . visual-line-mode)
         (prog-mode . (lambda () (setq-local sentence-end-double-space t))))
  :config
  (setq-default sentence-end-double-space nil)
  (setopt sentence-end-without-period nil)
  (setopt colon-double-space nil)
  (setopt adaptive-fill-mode t))

;;; server
(use-package server
  :ensure nil
  :config
  (unless (server-running-p)
    (server-start))
  (require 'org-protocol))

;; spelling
(use-package ispell
  :ensure nil
  :config
  (ispell-set-spellchecker-params)
  (ispell-hunspell-add-multi-dic "en_US,id_ID")
  (add-to-list 'ispell-dictionary-alist
               '("en_US" "[[:alpha:]]" "[^[:alpha:]]" "['’]" nil ("-d" "en_US") nil utf-8))
  (setopt ispell-program-name (or (executable-find "ispell")
                                  (executable-find "hunspell")
                                  (executable-find "aspell"))
          ispell-dictionary "en_US,id_ID"
          ispell-personal-dictionary (expand-file-name ".hunspell_personal" (getenv "XDG_DATA_HOME"))))

(unless (file-exists-p ispell-personal-dictionary)
  (write-region "" nil ispell-personal-dictionary nil 0))

(use-package flyspell
  :ensure nil)

;;; `help'
(use-package help
  :ensure nil
  :config
  (setopt help-window-select t))

;;; `org-mode'
(use-package org
  :ensure nil
  :demand t
  :commands org-tempo
  :hook (org-mode . flyspell-mode)
  :hook ((org-mode . org-indent-mode)
         (org-mode . +config/org-prettify-symbols))
  :config
  (cond ((file-directory-p (expand-file-name "braindump/org" org-directory))
         (customize-set-variable '+config/org-roam-directory
                                 (expand-file-name "braindump/org" org-directory)
                                 "`+config/org-roam-directory' set inside `org-directory'"))
        ((file-directory-p (expand-file-name "Projects/personal/braindump/org" (getenv "HOME")))
         (customize-set-variable '+config/org-roam-directory
                                 (expand-file-name "Projects/personal/braindump/org" (getenv "HOME"))
                                 "`+config/org-roam-directory' set inside personal projects directory")))
  (cond ((file-directory-p (expand-file-name "alexforsale.github.io" org-directory))
         (customize-set-variable '+config/blog-directory
                                 (expand-file-name "alexforsale.github.io" org-directory)
                                 "`+config/blog-directory' set inside `org-directory'"))
        ((file-directory-p (expand-file-name "Projects/personal/alexforsale.github.io" (getenv "HOME")))
         (customize-set-variable '+config/blog-directory
                                 (expand-file-name "Projects/personal/alexforsale.github.io" (getenv "HOME"))
                                 "`+config/blog-directory' set inside personal projects directory")))
  (modify-syntax-entry ?= "$" org-mode-syntax-table)
  (modify-syntax-entry ?~ "$" org-mode-syntax-table)
  (modify-syntax-entry ?_ "$" org-mode-syntax-table)
  (modify-syntax-entry ?+ "$" org-mode-syntax-table)
  (modify-syntax-entry ?/ "$" org-mode-syntax-table)
  (modify-syntax-entry ?* "$" org-mode-syntax-table)
  (add-to-list 'org-modules 'org-tempo t)
  (add-to-list 'org-structure-template-alist '("sh" . "src sh"))
  (add-to-list 'org-structure-template-alist '("co" . "src conf"))
  (add-to-list 'org-structure-template-alist '("lisp" . "src lisp"))
  (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
  (add-to-list 'org-structure-template-alist '("sc" . "src scheme"))
  (add-to-list 'org-structure-template-alist '("ts" . "src typescript"))
  (add-to-list 'org-structure-template-alist '("py" . "src python"))
  (add-to-list 'org-structure-template-alist '("go" . "src go"))
  (add-to-list 'org-structure-template-alist '("yaml" . "src yaml"))
  (add-to-list 'org-structure-template-alist '("js" . "src js"))
  (add-to-list 'org-structure-template-alist '("json" . "src json"))
  (add-to-list 'org-structure-template-alist '("n" . "note"))
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((emacs-lisp . t)
     (awk . t)
     (C . t)
     (css . t)
     (calc . t)
     (ditaa . t) ; needs the `ditaa' package
     (dot . t ) ; `graphviz'
     (screen . t)
     (haskell . t)
     (java . t)
     (js . t)
     (latex . t)
     (lisp . t)
     (lua . t)
     (org . t)
     (perl . t)
     (plantuml . t)
     (python .t)
     (ruby . t)
     (shell . t)
     (sed . t)
     (scheme . t)
     (sql . t)
     (sqlite . t)))
  (setq-default org-use-sub-superscripts '{})
  (add-to-list 'org-babel-tangle-lang-exts '("js" . "js"))
  (defun +config/org-prettify-symbols ()
    (push '("[ ]" . "☐") prettify-symbols-alist)
    (push '("[X]" . "☑") prettify-symbols-alist)
    (prettify-symbols-mode t))
  (require 'org-tempo)
  :custom
  (org-highlight-latex-and-related nil)
  (org-replace-disputed-keys t)
  (org-indirect-buffer-display 'current-window)
  (org-enforce-todo-dependencies t)
  (org-fontify-whole-heading-line t)
  (org-return-follows-link t)
  (org-mouse-1-follows-link t)
  (org-image-actual-width nil)
  (org-adapt-indentation nil)
  (org-startup-indented t)
  (org-link-descriptive nil)
  (org-log-done 'time)
  (org-log-refile 'time)
  (org-log-redeadline 'time)
  (org-log-reschedule 'time)
  (org-log-into-drawer t)
  (org-clone-delete-id t)
  (org-default-notes-file (expand-file-name "notes.org" org-directory))
  (org-insert-heading-respect-content nil)
  (org-pretty-entities t)
  (org-use-property-inheritance t)
  (org-priority-highest ?A)
  (org-priority-lowest ?D)
  (org-priority-default ?B)
  (org-todo-keywords
   '((sequence
      "TODO(t!)"  ; A task that needs doing & is ready to do
      "NEXT(n!)"  ; Tasks that can be delayed
      "PROG(p!)"  ; A task that is in progress
      "WAIT(w!)"  ; Something external is holding up this task
      "HOLD(h!)"  ; This task is paused/on hold because of me
      "|"
      "DONE(d!)"  ; Task successfully completed
      "DELEGATED(l!)" ; Task is delegated
      "NOTES(o!)" ; set as notes
      "KILL(k!)") ; Task was cancelled, aborted or is no longer applicable
     )))

(global-set-key (kbd "C-c l") #'org-store-link)
(global-set-key (kbd "C-c a") #'org-agenda)
(global-set-key (kbd "C-c c") #'org-capture)

(use-package org-entities
  :ensure nil
  :config
  (setopt org-entities-user
          '(("flat"  "\\flat" nil "" "" "266D" "♭")
            ("sharp" "\\sharp" nil "" "" "266F" "♯"))))

(use-package org-faces
  :ensure nil
  :custom
  (org-fontify-quote-and-verse-blocks t))

(use-package org-archive
  :ensure nil
  :after org
  :custom
  (org-archive-tag "archive")
  (org-archive-subtree-save-file-p t)
  (org-archive-mark-done t)
  (org-archive-reversed-order t)
  (org-archive-location (concat (expand-file-name "archives.org" org-directory) "::datetree/* Archived Tasks")))

(use-package org-capture
  :after org
  :ensure nil
  :demand t
  :config
  (org-capture-put :kill-buffer t)
  (setq org-capture-templates ;; this is the default from `doom'.
        `(("i" "Inbox - Goes Here first!" entry
           (file+headline ,(expand-file-name "inbox.org" org-directory) "Inbox")
           "** %?\n%i\n%a" :prepend t)
          ;; ("r" "Request" entry (file+headline ,(expand-file-name "inbox.org" org-directory) "Request")
          ;;  (file ,(expand-file-name "request.template" org-directory)))
          ("l" "Links" entry
           (file+headline ,(expand-file-name "links.org" org-directory) "Links")))))

(use-package org-refile
  :ensure nil
  :after org
  :hook (org-after-refile-insert . save-buffer)
  :custom
  (org-refile-targets
   `((,(expand-file-name "projects.org" org-directory) :maxlevel . 1)
     (,(expand-file-name "notes.org" org-directory) :maxlevel . 1)
     (,(expand-file-name "routines.org" org-directory) :maxlevel . 3)
     (,(expand-file-name "personal.org" org-directory) :maxlevel . 1)))
  (org-refile-use-outline-path 't)
  (org-outline-path-complete-in-steps nil))

(use-package org-fold
  :ensure nil
  :custom
  (org-fold-catch-invisible-edits 'smart))

(use-package org-id
    :ensure nil
    :after org
    :custom
    (org-id-locations-file-relative t)
    (org-id-link-to-org-use-id 'create-if-interactive-and-no-custom-id))

(use-package org-num
    :ensure nil
    :after org
    :custom
    (org-num-face '(:inherit org-special-keyword :underline nil :weight bold))
    (org-num-skip-tags '("noexport" "nonum")))

(use-package org-crypt ; built-in
    :ensure nil
    :after org
    :commands org-encrypt-entries org-encrypt-entry org-decrypt-entries org-decrypt-entry
    ;;:hook (org-reveal-start . org-decrypt-entry)
    :preface
    ;; org-crypt falls back to CRYPTKEY property then `epa-file-encrypt-to', which
    ;; is a better default than the empty string `org-crypt-key' defaults to.
    (defvar org-crypt-key nil)
    (with-eval-after-load 'org
      (add-to-list 'org-tags-exclude-from-inheritance "crypt"))
    :config
    (setopt epa-file-encrypt-to "alexforsale@yahoo.com"))

(use-package org-attach
    :ensure nil
    :after org
    :commands (org-attach-new
               org-attach-open
               org-attach-open-in-emacs
               org-attach-reveal-in-emacs
               org-attach-url
               org-attach-set-directory
               org-attach-sync)
    :config
    (unless org-attach-id-dir
      (setq-default org-attach-id-dir (expand-file-name ".attach/" org-directory)))
    (with-eval-after-load 'projectile
      (add-to-list 'projectile-globally-ignored-directories org-attach-id-dir))
    :custom
    (org-attach-auto-tag nil))

(use-package org-agenda
    :ensure nil
    :after org
    :custom
    (org-agenda-breadcrumbs-separator " → ")
    (org-agenda-files (list (concat org-directory "/")))
    (org-agenda-file-regexp "\\`[^.].*\\.org\\|[0-9]+$\\'")
    (org-agenda-include-inactive-timestamps t)
    (org-agenda-window-setup 'only-window)
    (org-stuck-projects '("+{project*}-killed-Archives/-DONE-KILL-DELEGATED"
                          ("TODO" "NEXT" "IDEA" "PROG")
                          nil ""))
    :config
    (with-eval-after-load 'evil
      (evil-set-initial-state #'org-agenda-mode 'normal)
      (evil-define-key 'normal org-agenda-mode-map "q" 'org-agenda-quit))
    (setopt org-agenda-custom-commands
          `(("w" "Work Agenda and all TODOs"
             ((agenda ""
                      ((org-agenda-span 1)
                       (org-agenda-start-on-weekday t)
                       (org-agenda-block-separator nil)
                       (org-agenda-use-time-grid t)
                       (org-agenda-day-face-function (lambda (date) 'org-agenda-date))
                       (org-agenda-format-date "%A %-e %B %Y")
                       (org-agenda-overriding-header "\nToday\n")))
              (tags-todo "TODO=\"TODO\"|\"NEXT\""
                         ((org-agenda-block-separator nil)
                          (org-agenda-skip-function '(org-agenda-skip-if-todo 'nottodo 'done))
                          (org-agenda-use-time-grid nil)
                          (org-agenda-overriding-header "\nIncomplete\n")))
              (agenda ""
                      ((org-agenda-span 7)
                       (org-agenda-start-on-weekday 1)
                       (org-agenda-block-separator nil)
                       (org-agenda-use-time-grid nil)
                       (org-agenda-overriding-header "\nWeekly\n"))))
             ((org-agenda-tag-filter-preset '("-personal" "-home"))))
            ("h" "Home Agenda and all personal TODOs"
             ((agenda ""
                      ((org-agenda-span 1)
                       (org-agenda-start-on-weekday t)
                       (org-agenda-block-separator nil)
                       (org-agenda-use-time-grid t)
                       (org-agenda-day-face-function (lambda (date) 'org-agenda-date))
                       (org-agenda-format-date "%A %-e %B %Y")
                       (org-agenda-overriding-header "\nToday\n")))
              (tags-todo "TODO=\"TODO\"|\"NEXT\""
                         ((org-agenda-block-separator nil)
                          (org-agenda-skip-function '(org-agenda-skip-if-todo 'nottodo 'done))
                          (org-agenda-use-time-grid nil)
                          (org-agenda-overriding-header "\nIncomplete\n")))
              (agenda ""
                      ((org-agenda-span 7)
                       (org-agenda-start-on-weekday 1)
                       (org-agenda-block-separator nil)
                       (org-agenda-use-time-grid nil)
                       (org-agenda-overriding-header "\nWeekly\n"))))
             ;; ((org-agenda-tag-filter-preset '("+personal")))
             ))))

(use-package org-clock
    :ensure nil
    :after org
    :commands org-clock-save
    :hook (kill-emacs . org-clock-save)
    :custom
    (org-persist 'history)
    (org-clock-in-resume t)
    (org-clock-out-remove-zero-time-clocks t)
    (org-clock-history-length 20)
    (org-show-notification-handler "notify-send")
    (org-agenda-skip-scheduled-if-deadline-is-shown t)
    :config
    (org-clock-persistence-insinuate))

(use-package org-timer
    :ensure nil
    :config
    (setopt org-timer-format "Timer :: %s"))

(use-package org-contrib)

(use-package org-eldoc
  :ensure nil
  :after org org-contrib
  :config
  (puthash "org" #'ignore org-eldoc-local-functions-cache)
  ;;(puthash "plantuml" #'ignore org-eldoc-local-functions-cache)
  (puthash "python" #'python-eldoc-function org-eldoc-local-functions-cache)
  :custom
  (org-eldoc-breadcrumb-separator " → "))

(use-package pdf-tools
  :config
  (pdf-tools-install)
  (setq-default pdf-view-display-size 'fit-width)
  (define-key pdf-view-mode-map (kbd "C-s") 'isearch-forward)
  :custom
  (pdf-annot-activate-created-annotations t "automatically annotate highlights"))

;;; `prog-mode'
;;; delete trailing whitespace and enable `electric-pair-local-mode'
(use-package prog-mode
  :ensure nil
  :hook
  (prog-mode . (lambda ()
                 (add-hook 'before-save-hook 'delete-trailing-whitespace nil t)
                 (electric-pair-local-mode 1))))

(use-package display-line-numbers
  :ensure nil
  :hook (prog-mode . display-line-numbers-mode)
  :config
  (setopt display-line-numbers-type 'relative))

;;; eglot
(use-package eglot
  :ensure nil
  :config
  (add-to-list 'eglot-server-programs
               '((nix-mode nix-ts-mode)
                 . ("nixd" "--semantic-tokens" "--inlay-hints"
                    :initializationOptions (:nixd (:formatting.command "nixpkgs-fmt"))))))

;;; python
(add-to-list 'major-mode-remap-alist '(python-mode . python-ts-mode))

(use-package python-ts-mode
  :ensure nil
  :hook (python-ts-mode . eglot-ensure))

;;; make-mode
(use-package make-mode
  :ensure nil
  :config
  (add-hook 'makefile-mode-hook 'indent-tabs-mode))

;;; external packages
(use-package magit
  :demand t
  :config
  (setopt magit-revision-show-gravatars '("^Author:     " . "^Commit:     ")))

;;; `markdown-mode'
(use-package markdown-mode)

;;; nix-ts-mode
(use-package nix-ts-mode
  :mode "\\.nix\\'"
  :hook
  ((nix-ts-mode . (lambda () (setq-local tab-width 2)))
   (nix-ts-mode . eglot-ensure)))

;;; multiple-cursors
(use-package multiple-cursors
  :bind
  (("C->" . mc/mark-next-like-this)
   ("C-<" . mc/mark-previous-like-this)
   ("C-c C-<" . mc/mark-all-like-this)
   ("C-S-c C-S-c" . mc/edit-lines)))

(defvar my/mc-repeat-map
  (let ((map (make-sparse-keymap)))
    (define-key map ">" #'mc/mark-next-like-this)
    (define-key map "<" #'mc/mark-previous-like-this)
    map)
  "Keymap for my/mc-repeat-map")
(put 'mc/mark-next-like-this 'repeat-map 'my/mc-repeat-map)
(put 'mc/mark-previous-like-this 'repeat-map 'my/mc-repeat-map)

;;; rainbow
(use-package rainbow-mode
  :hook (prog-mode . rainbow-mode)
  :config
  (setopt rainbow-html-colors-major-mode-list
  	'(prog-mode conf-mode html-mode css-mode php-mode nxml-mode xml-mode)
  	rainbow-html-colors t))

(use-package rainbow-identifiers
  :hook (prog-mode . rainbow-identifiers-mode))

(use-package rainbow-delimiters
  :hook (prog-mode . rainbow-delimiters-mode)
  :config
  (setopt rainbow-delimiters-max-face-count 4))

(use-package indent-bars
  :hook (prog-mode . indent-bars-mode))

(use-package org-rainbow-tags)
