(setopt user-mail-address "alexforsale@yahoo.com"
        user-full-name "Kristian Alexander P")

(cond ((file-directory-p (expand-file-name "Sync/org" (getenv "HOME")))
       (customize-set-variable '+config/org-directory (expand-file-name "Sync/org" (getenv "HOME"))))
      ((string-match-p "microsoft" (shell-command-to-string "uname -a"))
       (if (file-directory-p "/mnt/c/Users/SyncthingServiceAcct/Default Folder/org")
           (customize-set-variable '+config/org-directory "/mnt/c/Users/SyncthingServiceAcct/Default Folder/org"))))

(use-package delsel
  :ensure nil
  :config
  (delete-selection-mode 1))

(use-package emacs
  :ensure nil
  :config
  (transient-mark-mode 1)
  (setopt use-short-answers t
	  delete-by-moving-to-trash t
	  load-prefer-newer t
	  read-buffer-completion-ignore-case t
	  read-file-name-completion-ignore-case t
	  inhibit-startup-screen t))

(use-package font-core
  :ensure nil
  :config
  (global-font-lock-mode 1))

(use-package winner
  :ensure nil
  :init
  (winner-mode +1)
  :config
  (setopt winner-boring-buffers '("*Completions*" "*Compile-Log*" "*inferior-lisp*" "*Fuzzy Completions*"
                                  "*Apropos*" "*Help*" "*cvs*" "*Buffer List*" "*Ibuffer*"
                                  "*esh command on file*")))

(use-package completion-preview
  :ensure nil
  :config
  (global-completion-preview-mode)
  (push 'org-self-insert-command completion-preview-commands))

(use-package minibuffer
  :ensure nil
  :config
  (setopt minibuffer-visible-completions t
	  completion-styles '(basic flex partial-completion emacs22)))

(use-package simple
  :ensure nil
  :config
  (global-visual-line-mode t)
  (column-number-mode t)
  (line-number-mode t)
  (setopt completion-auto-wrap t
	  completion-auto-select t
	  completion-auto-help 'visible
	  completion-ignore-case t)
  (setq-default indent-tabs-mode nil))

(use-package saveplace
  :init
  (save-place-mode 1))

(use-package recentf
  :bind ("C-c f" . recentf)
  :commands recentf-open-files
  :init
  (recentf-mode 1)
  :custom
  (recentf-auto-cleanup t)
  (recentf-max-saved-items 250)
  (recentf-max-menu-items 300)
  (recentf-exclude
   `("/elpa/" ;; ignore all files in elpa directory
     "recentf" ;; remove the recentf load file
     ".*?autoloads.el$"
     "treemacs-persist"
     "company-statistics-cache.el" ;; ignore company cache file
     "/intero/" ;; ignore script files generated by intero
     "/journal/" ;; ignore daily journal files
     ".gitignore" ;; ignore `.gitignore' files in projects
     "/tmp/" ;; ignore temporary files
     "NEWS" ;; don't include the NEWS file for recentf
     "bookmarks"  "bmk-bmenu" ;; ignore bookmarks file in .emacs.d
     "loaddefs.el"
     "^/\\(?:ssh\\|su\\|sudo\\)?:" ;; ignore tramp/ssh files
     (concat "^" (regexp-quote (or (getenv "XDG_RUNTIME_DIR")
                                   "/run"))))))
(use-package which-key
  :ensure nil
  :init
  (which-key-mode 1))

(use-package files
  :ensure nil
  :hook
  ((prog-mode text-mode) . auto-save-visited-mode)
  :config
  (auto-save-visited-mode 1)
  (nconc
   auto-mode-alist
   '(("/LICENSE\\'" . text-mode)
     ("\\.log\\'" . text-mode)
     ("rc\\'" . conf-mode)
     ("\\.\\(?:hex\\|nes\\)\\'" . hexl-mode)))
  (setopt auto-save-visited-interval 10
	  revert-without-query (list ".")
	  find-file-suppress-same-file-warnings t
	  find-file-visit-truename t
	  confirm-kill-processes nil
	  version-control t
	  backup-by-copying t
	  backup-directory-alist `(("." . ,(expand-file-name ".backup" user-emacs-directory)))
	  auto-save-list-file-prefix (expand-file-name ".autosave/" user-emacs-directory)
	  require-final-newline t
	  find-file-visit-truename t
	  auto-mode-case-fold nil)
  :hook
  ((prog-mode text-mode) . auto-save-visited-mode))

(use-package savehist
  :ensure nil
  :config
  (savehist-mode 1)
  (setopt savehist-additional-variables
	  '(command-history
	    kill-ring
	    register-alist
	    mark-ring
	    global-mark-ring
	    search-ring
	    regexp-search-ring)))

(use-package project
  :ensure nil
  :config
  (setopt project-mode-line t))
