;;; identity
(setopt user-mail-address "alexforsale@yahoo.com"
        user-full-name "Kristian Alexander P")

;;; `+config/org-directory'
(cond ((file-directory-p (expand-file-name "Sync/org" (getenv "HOME")))
       (customize-set-variable '+config/org-directory (expand-file-name "Sync/org" (getenv "HOME"))))
      ((string-match-p "microsoft" (shell-command-to-string "uname -a"))
       (if (file-directory-p "/mnt/c/Users/SyncthingServiceAcct/Default Folder/org")
           (customize-set-variable '+config/org-directory "/mnt/c/Users/SyncthingServiceAcct/Default Folder/org"))))

;;; custom functions
(defun my/move-line-or-region-internal (arg)
   (cond
    ((and mark-active transient-mark-mode)
     (if (> (point) (mark))
            (exchange-point-and-mark))
     (let ((column (current-column))
              (text (delete-and-extract-region (point) (mark))))
       (forward-line arg)
       (move-to-column column t)
       (set-mark (point))
       (insert text)
       (exchange-point-and-mark)
       (setq deactivate-mark nil)))
    (t
     (beginning-of-line)
     (when (or (> arg 0) (not (bobp)))
       (forward-line)
       (when (or (< arg 0) (not (eobp)))
            (transpose-lines arg))
       (forward-line -1)))))

(defun my/move-line-or-region-down (arg)
   "Move region (transient-mark-mode active) or current line
  arg lines down."
   (interactive "*p")
   (my/move-line-or-region-internal arg))

(defun my/move-line-or-region-up (arg)
   "Move region (transient-mark-mode active) or current line
  arg lines up."
   (interactive "*p")
   (my/move-line-or-region-internal (- arg)))

(global-set-key (kbd "C-c M-n") 'my/move-line-or-region-down)
(global-set-key (kbd "C-c M-p") 'my/move-line-or-region-up)

(defvar my/move-line-or-region-repeat-map
  (let ((map (make-sparse-keymap)))
    (define-key map "n" #'my/move-line-or-region-down)
    (define-key map "p" #'my/move-line-or-region-up)
    map)
  "Keymap for my/move-line-or-region-repeat-map")
(put 'my/move-line-or-region-down 'repeat-map 'my/move-line-or-region-repeat-map)
(put 'my/move-line-or-region-up 'repeat-map 'my/move-line-or-region-repeat-map)

;;; enable `delete-selection-mode'
(use-package delsel
  :ensure nil
  :config
  (delete-selection-mode 1))

(use-package emacs
  :ensure nil
  :config
  (transient-mark-mode 1)
  (setopt use-short-answers t
          delete-by-moving-to-trash t
          load-prefer-newer t
          read-buffer-completion-ignore-case t
          read-file-name-completion-ignore-case t
          inhibit-startup-screen t
          indicate-empty-lines t
          frame-resize-pixelwise t))

(use-package repeat
  :ensure nil
  :config
  (repeat-mode 1))

(use-package font-core
  :ensure nil
  :config
  (global-font-lock-mode 1))

(use-package winner
  :ensure nil
  :init
  (winner-mode +1)
  :config
  (setopt winner-boring-buffers '("*Completions*" "*Compile-Log*" "*inferior-lisp*" "*Fuzzy Completions*"
                                  "*Apropos*" "*Help*" "*cvs*" "*Buffer List*" "*Ibuffer*"
                                  "*esh command on file*")))

(use-package completion-preview
  :ensure nil
  :config
  (global-completion-preview-mode)
  (push 'org-self-insert-command completion-preview-commands))

(use-package minibuffer
  :ensure nil
  :config
  (setopt minibuffer-visible-completions t
          completion-styles '(basic partial-completion flex emacs22)))

(use-package simple
  :ensure nil
  :config
  (global-visual-line-mode t)
  (column-number-mode t)
  (line-number-mode t)
  (setopt completion-auto-wrap t
          completion-auto-select 'second-tab
          completion-auto-help nil
          completion-ignore-case t)
  (setq-default indent-tabs-mode nil))

(use-package saveplace
  :init
  (save-place-mode 1))

(use-package recentf
  :bind ("C-c f" . recentf)
  :commands recentf-open-files
  :init
  (recentf-mode 1)
  :custom
  (recentf-auto-cleanup t)
  (recentf-max-saved-items 250)
  (recentf-max-menu-items 300)
  (recentf-exclude
   `("/elpa/" ;; ignore all files in elpa directory
     "recentf" ;; remove the recentf load file
     ".*?autoloads.el$"
     "treemacs-persist"
     "company-statistics-cache.el" ;; ignore company cache file
     "/intero/" ;; ignore script files generated by intero
     "/journal/" ;; ignore daily journal files
     ".gitignore" ;; ignore `.gitignore' files in projects
     "/tmp/" ;; ignore temporary files
     "NEWS" ;; don't include the NEWS file for recentf
     "bookmarks"  "bmk-bmenu" ;; ignore bookmarks file in .emacs.d
     "loaddefs.el"
     "^/\\(?:ssh\\|su\\|sudo\\)?:" ;; ignore tramp/ssh files
     (concat "^" (regexp-quote (or (getenv "XDG_RUNTIME_DIR")
                                   "/run"))))))

(use-package autorevert
  :ensure nil
  :config
  (global-auto-revert-mode t)
  (setopt auto-revert-interval 60
          global-auto-revert-non-file-buffers t))

(use-package which-key
  :ensure nil
  :init
  (which-key-mode 1))

(use-package files
  :ensure nil
  :hook
  ((prog-mode text-mode) . auto-save-visited-mode)
  :config
  (auto-save-visited-mode 1)
  (nconc
   auto-mode-alist
   '(("/LICENSE\\'" . text-mode)
     ("\\.log\\'" . text-mode)
     ("rc\\'" . conf-mode)
     ("\\.\\(?:hex\\|nes\\)\\'" . hexl-mode)))
  (setopt auto-save-visited-interval 10
          revert-without-query (list ".")
          find-file-suppress-same-file-warnings t
          find-file-visit-truename t
          confirm-kill-processes nil
          version-control t
          backup-by-copying t
          backup-directory-alist `(("." . ,(expand-file-name ".backup" user-emacs-directory)))
          auto-save-list-file-prefix (expand-file-name ".autosave/" user-emacs-directory)
          require-final-newline t
          find-file-visit-truename t
          auto-mode-case-fold nil)
  :hook
  ((prog-mode text-mode) . auto-save-visited-mode))

(use-package savehist
  :ensure nil
  :config
  (savehist-mode 1)
  (setopt savehist-additional-variables
          '(command-history
            kill-ring
            register-alist
            mark-ring
            global-mark-ring
            search-ring
            regexp-search-ring)))

(use-package project
  :ensure nil
  :config
  (setopt project-mode-line t))

(use-package mouse
  :ensure nil
  :config
  (setopt mouse-yank-at-point t))

(use-package subword
  :ensure nil
  :init
  (global-subword-mode 1))

(use-package text-mode
  :ensure nil
  :hook (((text-mode prog-mode) . visual-line-mode)
         (prog-mode . (lambda () (setq-local sentence-end-double-space t))))
  :config
  (setq-default sentence-end-double-space nil)
  (setopt sentence-end-without-period nil)
  (setopt colon-double-space nil)
  (setopt adaptive-fill-mode t))

(use-package server
  :ensure nil
  :config
  (unless (server-running-p)
    (server-start))
  (require 'org-protocol))

;; spelling
(use-package ispell
  :ensure nil
  :config
  (ispell-set-spellchecker-params)
  (ispell-hunspell-add-multi-dic "en_US,id_ID")
  (add-to-list 'ispell-dictionary-alist
               '("en_US" "[[:alpha:]]" "[^[:alpha:]]" "['’]" nil ("-d" "en_US") nil utf-8))
  (setopt ispell-program-name (or (executable-find "ispell")
                                  (executable-find "hunspell")
                                  (executable-find "aspell"))
          ispell-dictionary "en_US,id_ID"
          ispell-personal-dictionary (expand-file-name ".hunspell_personal" (getenv "XDG_DATA_HOME"))))

(unless (file-exists-p ispell-personal-dictionary)
  (write-region "" nil ispell-personal-dictionary nil 0))

(use-package flyspell
  :ensure nil)

;;; `org-mode'
(use-package org
  :ensure nil
  :demand t
  :commands org-tempo
  :hook (org-mode . flyspell-mode)
  :hook ((org-mode . org-indent-mode)
         (org-mode . +config/org-prettify-symbols))
  :config
  (defun +config/org-mode-keybindings ()
    (global-set-key (kbd "C-c l") #'org-store-link)
    (global-set-key (kbd "C-c a") #'org-agenda)
    (global-set-key (kbd "C-c c") #'org-capture))
  (cond ((file-directory-p (expand-file-name "braindump/org" org-directory))
         (customize-set-variable '+config/org-roam-directory
                                 (expand-file-name "braindump/org" org-directory)))
        ((file-directory-p (expand-file-name "Projects/personal/braindump/org" (getenv "HOME")))
         (customize-set-variable '+config/org-roam-directory
                                 (expand-file-name "Projects/personal/braindump/org" (getenv "HOME")))))
  (cond ((file-directory-p (expand-file-name "alexforsale.github.io" org-directory))
         (customize-set-variable '+config/blog-directory
                                 (expand-file-name "alexforsale.github.io" org-directory)))
        ((file-directory-p (expand-file-name "Projects/personal/alexforsale.github.io" (getenv "HOME")))
         (customize-set-variable '+config/blog-directory
                                 (expand-file-name "Projects/personal/alexforsale.github.io" (getenv "HOME")))))
  (modify-syntax-entry ?= "$" org-mode-syntax-table)
  (modify-syntax-entry ?~ "$" org-mode-syntax-table)
  (modify-syntax-entry ?_ "$" org-mode-syntax-table)
  (modify-syntax-entry ?+ "$" org-mode-syntax-table)
  (modify-syntax-entry ?/ "$" org-mode-syntax-table)
  (modify-syntax-entry ?* "$" org-mode-syntax-table)
  (add-to-list 'org-modules 'org-tempo t)
  (add-to-list 'org-structure-template-alist '("sh" . "src sh"))
  (add-to-list 'org-structure-template-alist '("co" . "src conf"))
  (add-to-list 'org-structure-template-alist '("lisp" . "src lisp"))
  (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
  (add-to-list 'org-structure-template-alist '("sc" . "src scheme"))
  (add-to-list 'org-structure-template-alist '("ts" . "src typescript"))
  (add-to-list 'org-structure-template-alist '("py" . "src python"))
  (add-to-list 'org-structure-template-alist '("go" . "src go"))
  (add-to-list 'org-structure-template-alist '("yaml" . "src yaml"))
  (add-to-list 'org-structure-template-alist '("js" . "src js"))
  (add-to-list 'org-structure-template-alist '("json" . "src json"))
  (add-to-list 'org-structure-template-alist '("n" . "note"))
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((emacs-lisp . t)
     (awk . t)
     (C . t)
     (css . t)
     (calc . t)
     (ditaa . t) ; needs the `ditaa' package
     (dot . t ) ; `graphviz'
     (screen . t)
     (haskell . t)
     (java . t)
     (js . t)
     (latex . t)
     (lisp . t)
     (lua . t)
     (org . t)
     (perl . t)
     (plantuml . t)
     (python .t)
     (ruby . t)
     (shell . t)
     (sed . t)
     (scheme . t)
     (sql . t)
     (sqlite . t)))
  (setq-default org-use-sub-superscripts '{})
  (add-to-list 'org-babel-tangle-lang-exts '("js" . "js"))
  (defun +config/org-prettify-symbols ()
    (push '("[ ]" . "☐") prettify-symbols-alist)
    (push '("[X]" . "☑") prettify-symbols-alist)
    (prettify-symbols-mode t))
  (require 'org-tempo)
  :custom
  (org-highlight-latex-and-related nil)
  (org-replace-disputed-keys t)
  (org-indirect-buffer-display 'current-window)
  (org-enforce-todo-dependencies t)
  (org-fontify-whole-heading-line t)
  (org-return-follows-link t)
  (org-mouse-1-follows-link t)
  (org-image-actual-width nil)
  (org-adapt-indentation nil)
  (org-startup-indented t)
  (org-link-descriptive nil)
  (org-log-done 'time)
  (org-log-refile 'time)
  (org-log-redeadline 'time)
  (org-log-reschedule 'time)
  (org-log-into-drawer t)
  (org-clone-delete-id t)
  (org-default-notes-file (expand-file-name "notes.org" org-directory))
  (org-insert-heading-respect-content nil)
  (org-pretty-entities t)
  (org-use-property-inheritance t)
  (org-priority-highest ?A)
  (org-priority-lowest ?D)
  (org-priority-default ?B)
  (org-todo-keywords
   '((sequence
      "TODO(t!)"  ; A task that needs doing & is ready to do
      "NEXT(n!)"  ; Tasks that can be delayed
      "PROG(p!)"  ; A task that is in progress
      "WAIT(w!)"  ; Something external is holding up this task
      "HOLD(h!)"  ; This task is paused/on hold because of me
      "|"
      "DONE(d!)"  ; Task successfully completed
      "DELEGATED(l!)" ; Task is delegated
      "NOTES(o!)" ; set as notes
      "KILL(k!)") ; Task was cancelled, aborted or is no longer applicable
     )))

(use-package icomplete
  :ensure nil
  :config
  (fido-vertical-mode 1))

;;; `prog-mode'
(use-package prog-mode
  :ensure nil
  :hook
  (prog-mode . (lambda () (add-hook 'before-save-hook 'delete-trailing-whitespace nil t))))

;;; eglot
(use-package eglot
  :ensure nil
  :config
  (add-to-list 'eglot-server-programs
               '((nix-mode nix-ts-mode)
                 . ("nixd" "--semantic-tokens" "--inlay-hints"
                    :initializationOptions (:nixd (:formatting.command "nixpkgs-fmt"))))))

;;; python
(add-to-list 'major-mode-remap-alist '(python-mode . python-ts-mode))

(use-package python-ts-mode
  :ensure nil
  :hook (python-ts-mode . eglot-ensure))

;;; external packages
(use-package magit
  :demand t
  :config
  (setopt magit-revision-show-gravatars '("^Author:     " . "^Commit:     ")))

(use-package nix-ts-mode
  :mode "\\.nix\\'"
  :hook
  ((nix-ts-mode . (lambda () (setq-local tab-width 2)))
   (nix-ts-mode . eglot-ensure))
  :config
  (setopt lsp-nix-nixd-nixos-options-expr
            (concat "(builtins.getFlake \"/etc/nixos\").nixosConfigurations." system-name ".options")
            lsp-nix-nixd-home-manager-options-expr
            (concat "(builtins.getFlake \"/etc/nixos\").homeConfigurations." "\"" user-login-name "@" system-name "\".options")
            lsp-nix-nixd-nixpkgs-expr "import (builtins.getFlake \"/etc/nixos\").input.nixpkgs { }"
            lsp-nix-nixd-server-path (executable-find "nixd")
            lsp-nix-nixd-formatting-command ["nixpkgs-fmt"]))

(use-package multiple-cursors
  :bind
  (("C->" . mc/mark-next-like-this)
   ("C-<" . mc/mark-previous-like-this)
   ("C-c C-<" . mc/mark-all-like-this)
   ("C-S-c C-S-c" . mc/edit-lines))
  :config
  (defvar my/mc-repeat-map
    (let ((map (make-sparse-keymap)))
      (define-key map ">" #'mc/mark-next-like-this)
      (define-key map "<" #'mc/mark-previous-like-this)
      map)
    "Keymap for my/mc-repeat-map")
  (put 'mc/mark-next-like-this 'repeat-map 'my/mc-repeat-map)
  (put 'mc/mark-previous-like-this 'repeat-map 'my/mc-repeat-map))
