#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil expand-links:t f:t
#+options: inline:t num:t p:nil pri:nil prop:nil stat:t tags:t
#+options: tasks:t tex:t timestamp:t title:t toc:t todo:t |:t
#+title: README
#+date: <2026-01-31 Sat>
#+author: Kristian Alexander P
#+email: alexforsale@yahoo.com
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 30.2 (Org mode 9.7.11)
#+cite_export:
* My Journey on Understanding Emacs's
** vc-mode
As long as I can remember, I have always use [[https://magit.vc/][magit]] in Emacs without even considering the alternative, the built in [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Version-Control.html][vc-mode]]. Vc-mode supports many different version control systems, while /magit/ is a text-based user interface for /git/.
*** How I use it
~C-x v d~ (=vc-dir=) is the entry point, invoke this on a project buffer to show the status on the current files, similar to =git status=. The commands I usually use while in this buffers:
- ~m~ :: mark a file/directory.
- ~u~ :: unmark a file/directory.
- ~M~ :: mark all the files with the same state as the current file. If on directory, mark all child files.
- ~U~ :: unmark all the files with the same state. If on directory, unmark all child files.
- ~i~ :: =vc-register=, ~git add~.
- ~P~ :: =vc-push=, ~git push~.
- ~+~ :: =vc-update=, like ~git pull~.
- ~=~ :: =vc-diff=, like ~git diff~.
- ~l~ :: =vc-print-log=, show log on the file on point.
- ~L~ :: =vc-print-root-log=, show the log (like ~git log --oneline~).
** project.el
Having always been a [[https://github.com/bbatsov/projectile][projectile]] user, the built in [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Projects.html][project.el]] is a new thing to me, but this is built in Emacs since around version 26. It's time to give it the proper attention.
*** Keybindings
- ~C-x p f~ :: =project-find-file=.
- ~C-x p g~ :: =project-find-regexp=.
- ~C-x p D~ :: =project-dired=.
- ~C-x p v~ :: =project-vc-dir=.
- ~C-x p b~ :: =project-switch-to-buffer=.
*** What I need
**** =git commit --amend= equivalent
With /magit/ I can use ~a~ to do an amend without having to have a file checked in.
** Base configuration
This is the perfect time to do a cleanup from my main Emacs [[https://github.com/alexforsale/literate-emacs][configuration]]. The things I have to set immediately:
- =delete-selection-mode= :: Replace selection when selection is active. Without this activated, I have to remove the selection first before placing another text.
- =transient-mark-mode= :: Highlight region, why this is not activated by default?
- =use-short-answers= :: =y= or =n= instead of =yes= or =no=.
- =which-key-mode= :: Now that =which-key= is builtin.
Other sane defaults I recommend:
- [[https://github.com/magnars/.emacs.d/blob/master/settings/sane-defaults.el][Magnars emacs.d]]
*** backup files
The common thing people have when editing files with Emacs is the =*~= files cluttering their working directory, also the autosave files (=#*=). The extreme solution is by not having backup at all (set the variable =make-backup-files= to ~nil~, and the variable =auto-save-default= to ~nil~). But I actually need to have a backup, so my solution is:
#+begin_SRC emacs-lisp
  (setopt backup-directory-alist `(("." . ,(expand-file-name ".backup" user-emacs-directory))))
#+end_SRC
and
#+begin_SRC emacs-lisp
  (setopt auto-save-list-file-prefix (expand-file-name ".autosave/" user-emacs-directory))
#+end_SRC
